### ISSUE TITLE
Can't hear eq effects when in any streaming app ex Spotify

### ISSUE THREAD

**Issue by piyushpaliwal** [pinpong/equalizer-issue-tracker#38]
I have tried several music streaming apps like Spotify; although the app has an option for setting the equalizer which takes you to the default system eq (which in my case is this app, MusicFX is disabled) and I don't hear any effects no matter what settings I choose, just plane flat music comes out. Works fine when I rum some mp3's downloaded locally. Can you please suggest something here.

-

Device info:
---
<table>
<tr><td>App version</td><td>1.3.2</td></tr>
<tr><td>App version code</td><td>13200</td></tr>
<tr><td>Android build version</td><td>2705526</td></tr>
<tr><td>Android release version</td><td>6.0.1</td></tr>
<tr><td>Android SDK version</td><td>23</td></tr>
<tr><td>Android build ID</td><td>MHC19Q</td></tr>
<tr><td>Device brand</td><td>google</td></tr>
<tr><td>Device manufacturer</td><td>Huawei</td></tr>
<tr><td>Device name</td><td>angler</td></tr>
<tr><td>Device model</td><td>Nexus 6P</td></tr>
<tr><td>Device product name</td><td>angler</td></tr>
<tr><td>Device hardware name</td><td>angler</td></tr>
<tr><td>ABIs</td><td>[arm64-v8a, armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (32bit)</td><td>[armeabi-v7a, armeabi]</td></tr>
<tr><td>ABIs (64bit)</td><td>[arm64-v8a]</td></tr>
</table>

**Comment by HeinrichReimer** [comment]
Spotify and some other straming services may not work properly because they dont provide us an audio session as e.g. Google Play Music does and as the platform docs prescribe. We added some legacy code for Spotify but that doesn't work on all devices...
We're incredibly sorry that you experience issues with music streaming services but for now all we can do is hope for Spotify updating their code to fit the Android documentation.
